### PR TITLE
Add Endless Ways collectibles

### PR DESCRIPTION
**Pull request by damian0815**
Add support for Endless Ways FA2 collectibles (mints). Replaces #267.

### CODE REVIEW

**Comment by melMass** [comment]
@damian0815 Any updates on this PR? 💘

**Comment by damian0815** [comment]
@melMass I wish 😞

**Comment by klassare** [comment]
We can't support this token in Kukai right now. There's no way to fetch the metadata. Usually this is an indication that the metadata isn't following the standards. We try to find the metadata in two ways, and both are failing.

BCD returns: `[]` ([example](https://api.better-call.dev/v1/contract/mainnet/KT1VdCrmZsQfuYgbQsezAHT1pXvs6zKF8xHB/tokens?token_id=10000000080&offset=0))

Taquito throws this error:
```
{
  message: "The protocol found in the URI is not supported: https."
  name: "ProtocolNotSupported"
  protocol: "https"
}
```

We are about to migrate fully from bcd to tzkt, and it's possible that will make it easier for us to mitigate this issue.

**Comment by damian0815** [comment]
@klassare i think there might be something wrong with how Kukai is calling Taquito. when i run this code here:
```
import { compose } from '@taquito/taquito';
import { tzip12 } from '@taquito/tzip12';
import { tzip16 } from '@taquito/tzip16';

...

const contractAddress = 'KT1VdCrmZsQfuYgbQsezAHT1pXvs6zKF8xHB';
const contract = await Tezos.contract.at(contractAddress, compose(tzip16, tzip12));
if (!contract) {
    throw new Error("Can't get contract");
}
const metadata = await contract.tzip12().getTokenMetadata(tokenId);
console.log("for token id", tokenId.toString(), "got metadata", metadata);
```
i get this output: 
```
for token id 10000000080 got metadata 
{
    "token_id": 10000000080,
    "artifactUri": "https://mainnet.live.endlessways.net/10000000080",
    "creators": "[\"tz1auPyXVaMy3GntdCQwH2VGNuFj6bAocj2v\"]",
    "decimals": 0,
    "description": "Prima, the first.",
    "displayUri": "https://mainnet.images.endlessways.net/displayImage/10000000080",
    "externalUri": "https://mainnet.endlessways.net/mint/10000000080",
    "formats": "[{\"uri\":\"https://mainnet.images.endlessways.net/displayImage/10000000080\",\"mimeType\":\"image/png\"},{\"uri\":\"https://mainnet.live.endlessways.net/10000000080\",\"mimeType\":\"text/html\",\"aspectRatio\":\"1\"}]",
    "isBooleanAmount": "true",
    "name": "Prima #81",
    "rights": "License: CC BY-NC-ND 4.0",
    "royalties": "{\"decimals\":3,\"shares\":{\"tz1auPyXVaMy3GntdCQwH2VGNuFj6bAocj2v\":100}}",
    "symbol": "EWY1",
    "thumbnailUri": "https://mainnet.images.endlessways.net/thumbnail/10000000080",
    "type": "text/html"
}
```

**Comment by damian0815** [comment]
i'm also unsure why https:// wouldn't be a supported procotol. is Kukai configured to only accept ipfs:// urls for the `''` (empty string) key in the fallback `token_metadata` bigmap?

**Comment by damian0815** [comment]
@klassare i've identified the problem (#305) and opened a new PR with a minimal fix (#307).

**Comment by klassare** [comment]
Replaced by #308
Thank you for working with us on this!

**Pull request closed without merging**
