### PR TITLE
enable tezos-storage: URI support in token metadata

### LINKED ISSUE #305: No support for tezos-storage: or https:// URIs when fetching contract→token metadata
TZIP-16 permits specifying `tezos-storage:` URIs for contract metadata ([ref](https://tzip.tezosagora.org/proposal/tzip-16/#metadata-uris)). However, contracts using this method fail to display correctly in Kukai. 

This causes token metadata fetch to fail, for example on Hangzhounet contracts `KT1JLMePd2SWnVxnxbgYiYDuXcpgocQGAQEi` or `KT1Q4n4aXtosJxvqywQfKViRpS3xqxitNpYG`, and mainnet contract `KT1VdCrmZsQfuYgbQsezAHT1pXvs6zKF8xHB`.

The reason can be found in the constructor for `TzktService`, where a `new MetadataProvider` is constructed without support for `https://` or `tezos-storage:`. The `MetadataProvider` should be configured to also accept `tezos-storage:`.

### PR DESCRIPTION
**Pull request by damian0815**
Fixes #305

### CODE REVIEW

**Comment by damian0815** [comment]
To add `http/https` support would involve adding `HttpHandler` (provided by Taquito) to the list of handlers - not sure if this has been deliberately excluded, though.

**Comment by klassare** [comment]
It's considered best practice to use ipfs. Objects on ipfs are immutable and hosted in a decentralized manner. Images served from http(s) can cause privacy leakage. But since Kukai uses a media proxy that risk is mitigated for us. But that can explain why you explicitly have to opt-in for it in Taquito.

**Comment by damian0815** [comment]
actually you don't have to opt-in - it's provided by Taquito OOTB. the reason why it's failing on Kukai is because Kukai excludes `https` and `tezos-storage` - which is custom behaviour, not default.

fwiw, objects on `tezos-storage` are also immutable, unless the contract author has provided a way to mutate them. using `tezos-storage` also removes dependency on IPFS (and the corresponding need to pin files).

**Comment by klassare** [comment]
We just discussed this internally and came to the same conclusion you just pointed out. We will approve this PR.

**Pull request merged**
