### PR TITLE
Adding information for the collection Basqunks on objkt

### PR DESCRIPTION
**Pull request by tamccullough**
Creating pull request to have the collection Basqunks added to the src/environment /environment.prod.ts file
I can be contacted through twitter
@tramccullough
Less likely to respond through my github account

### CODE REVIEW

**Comment by tezit** [comment]
We don't use twitter for communication. Hopefully you see the comments here. 

This pull request refers to your collection image `thumbnailUrl: "../../../assets/img/alias/basqunks0.png"` but the image is not included, please add it to the repo in this pull request. Also, at the bottom where you added your contract to the array of `TRUSTED_TOKEN_CONTRACTS` can you move it to the end of the array, instead of at the top. Thanks, if you can make those two changes this pull request will be merged very quickly.

**Comment by tamccullough** [comment]
How can I add the image without push access? Should I clone the repo and make the changes locally and is there a command that I should use to do the pull request? I have actually never attempted anything like this and just did the edits in the browser UI

**Comment by tezit** [comment]
I see you managed to add the image. But as its intended to be used only as a thumbnail, instead of a 5mb file, can you shrink it to no more than 600x600 and ideally less than 250kb

**Comment by klassare** [comment]
Resized the img in 522a184e5b1dd01431f0eb635baede157db133ff

**Comment by tamccullough** [comment]
Thank you so very much! Sorry that I forgot to resize the image!
Appreciate what you have done!

**Pull request merged**
