### PR TITLE
Add alias metadata & image for Chop Sumo, CUBE HEADs, and Cyber Gecko Gang

### PR DESCRIPTION
**Pull request by kevinelliott**
This adds some alias metadata and images for several large Tezos NFT releases.

* Chop Sumo (SUMO)
* CUBE HEADs (CUBE HEADs)
* Cyber Gecko Squad (Gecko)

Kukai users who have purchased these NFTs will benefit from this.

### CODE REVIEW

**Comment by tezit** [comment]
@kevinelliott it is better to split token support pull requests into one per token unless you are absolutely sure the data is accurate and approved by the projects. For example, in this PR the Chop Sumo info looks correct and is ready to approve and deploy. 

But the Gecko data, its unclear that name is accurately described -- do they really want to be known as "Gecko" only as in this PR or is the correct name "Cyber Gecko Gang" as on their website. Also, the image is var too big for a thumbnail, something smaller than 1.6mb would be easier to approve. 

For cube heads, there is only one contract provided, there is a name descrepancy, the PR has CUBE HEADs and objktcom refers to this collection as cubeheads all lower case. Ideally we do what the project lead wants as their name is what should be used. Finally what about the basqubes should that contract address be included in this "cubeheads" group?

**Comment by kevinelliott** [comment]
> @kevinelliott it is better to split token support pull requests into one per token unless you are absolutely sure the data is accurate and approved by the projects. For example, in this PR the Chop Sumo info looks correct and is ready to approve and deploy.
> 
> But the Gecko data, its unclear that name is accurately described -- do they really want to be known as "Gecko" only as in this PR or is the correct name "Cyber Gecko Gang" as on their website. Also, the image is var too big for a thumbnail, something smaller than 1.6mb would be easier to approve.
> 
> For cube heads, there is only one contract provided, there is a name descrepancy, the PR has CUBE HEADs and objktcom refers to this collection as cubeheads all lower case. Ideally we do what the project lead wants as their name is what should be used. Finally what about the basqubes should that contract address be included in this "cubeheads" group?

Agreed on all feedback! I will break this apart into separate PR's when I have a moment and we can address individually.

Also, which branch do you prefer this to ultimately be submitted against?

**Comment by tezit** [comment]
staging

**Comment by klassare** [comment]
CUBE HEADs included in https://github.com/kukai-wallet/kukai/pull/221

**Pull request closed without merging**
