### PR TITLE
Add fx(hash) marketplace contract

### PR DESCRIPTION
**Pull request by lenzfliker**
## Projection Information
Name:
fx(hash)

Contract:
https://better-call.dev/mainnet/KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE/operations

Marketplace website:
https://www.fxhash.xyz

Twitter:
https://twitter.com/fx_hash_

### CODE REVIEW

**Comment by lenzfliker** [comment]
@klassare snippet all good ser? 👀

**Comment by lenzfliker** [comment]
@klassare everything's alright?

**Comment by tezit** [comment]
@lenzfliker its on me to complete the review, will definitely get to it so that this makes it into a release very soon

**Comment by klassare** [comment]
Included in https://github.com/kukai-wallet/kukai/pull/221

**Comment by lenzfliker** [comment]
Thank you ser!

**Pull request closed without merging**
