### PR TITLE
Add support for correctly displaying Endless Ways tokens

### PR DESCRIPTION
**Pull request by damian0815**
Add Endless Ways logos and icons, and a new optional field `tokenIdOffset` to `TokenData` in `token.service.ts`.

My platform uses continuous token numbering across multiple contracts, and it starts at a non-zero token id. This means that I need to add an offset to the token id that Kukai calculates when displaying the token number, to make sure that, for example on Hangzhounet contract KT1U17aZt1fuFeHpkaFLTjoqbRngHEUa4JBw, token with id 90000000016 actually displays as "Endless Ways #90000000016", as desired, rather than "Endless Ways #17" (which would be incorrect).

To do this there's a new optional field on `TokenData`, `tokenIdOffset`, which is applied when rendering the token id. It can be used to account for continuous token id numbering across multiple contracts, or for non-0 starting token ids for a single contract.

(Note that TZIP-012 /  FA2 does not specify any requirement for token ids to start at 0, nor does it specify that they must monotonically increase.)

### CODE REVIEW

**Comment by damian0815** [comment]
For the purposes of clarification of why `tokenIdOffset` is necessary, please consider the following example, based on a real (testnet) wallet with real tokens.

Wallet `tz1Pr74UWHqSs3SjaLReqzhFmCw2826aZ9iJ` on Hangzhounet is the owner of contract (token id) KT1U17aZt1fuFeHpkaFLTjoqbRngHEUa4JBw (90000000016), KT1U17aZt1fuFeHpkaFLTjoqbRngHEUa4JBw (110000000009), KT1RPY1YEH9L1fp2Zy3DdByb5KukrP34XWcR (120000000002), and KT1EibnzPnFiCKtaN8EyUrhxyGk1N8XT1Tmu (150000000002). All of these are "Endless Ways" tokens, corresponding to mint 17 on [Artwork 9](https://greenroom.endlessways.net/artworks/9), mint 10 on [Artwork 11](https://greenroom.endlessways.net/artworks/11), mint 3 on [Artwork 12](https://greenroom.endlessways.net/artworks/12), and mint 3 on [Artwork 15](https://greenroom.endlessways.net/artworks/15), respectively. 

Here is how Kukai Wallet renders these tokens, without `tokenIdOffset`:
without-tokenIdOffset
None of these token ids correspond in any meaningful way to the token ids owned by the wallet. "Endless Ways #3" appears twice, incorrectly referring to different token ids on different contracts in each case. As a user, if I want to transfer these tokens to another wallet it is difficult to know how they correspond to artwork ids or mint numbers on Endless Ways without clicking all the way through to the `CONTRACT (ID)` UI. Displaying tokens in this way would lead to user confusion. 

However, if I use the code submitted as part of this PR, and supply appropriate values for `tokenIdOffset`, Kukai Wallet renders the tokens in a way that corresponds to the token ids, and thus in a way that the user can understand:
with-tokenIdOffset

**Comment by tezit** [comment]
I understand, but you might be confusing the "displaying of the token name" with the "more info" which includes the contract address and ID. We do not plan to add customization to the display name, this needs to be done via rich metadata standardization in tzip-021. We are tying to get interested parties (especially the marketplaces) to work on a token taxonomy for different token types and schemas which will enable apps/tools/wallets to better present tokens to users. It would be good for you to add this to the comments on tzip-021.

**Comment by damian0815** [comment]
Ok, thanks for clarifying. I removed `tokenIdOffset` and have managed to tweak the token indices so that Kukai displays what looks like the correct token ID in the display name. 

However, if I remove the entries from `CONSTANTS.ASSETS`, Kukai displays the tokens as Unknown Tokens. My contracts are TZIP-21 compliant, so I guess the question is why Kukai isn't picking up the token metadata? I am supplying it using the `token_metadata` off-chain view as defined in the FA2 standard.

**Comment by damian0815** [comment]
For reference, here's how the same wallet looks with Temple: 
temple

**Pull request closed without merging**
